name: build

on: [push, pull_request]

jobs:
  host-and-arm:
    runs-on: ubuntu-22.04

    steps:
    # ───────── Checkout ─────────
    - name: Checkout
      uses: actions/checkout@v4

    # ───────── Host build deps ─────────
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang clang-tidy zstd

    # ───────── Restore or seed SDK cache ─────────
    - name: Restore STM32MP1 SDK from cache
      id: sdk
      uses: actions/cache@v4
      with:
        path: /opt/st/SDK
        key: stm32mp1-sdk-6.6-scarthgap

    - name: One-time download & unpack SDK (if cache miss)
      if: steps.sdk.outputs.cache-hit != 'true'
      env:
        SDK_URL: ${{ secrets.SDK_URL }}      # set this repo secret to the stable GitHub-release URL
      run: |
        wget --quiet "$SDK_URL" -O /tmp/sdk.tar.zst
        sudo mkdir -p /opt               # create /opt if missing
        sudo tar -I zstd -xf /tmp/sdk.tar.zst -C /opt
        # after extract you have /opt/st/SDK/…  → exactly what the env-script expects

    # ───────── Host build & tests ─────────
    - name: Configure & build host-debug
      run: |
        cmake --preset host-debug
        cmake --build --preset host-debug
        ctest --preset host-debug --output-on-failure

    # ───────── ARM cross-build ─────────
    - name: Configure & build arm-release
      run: |
        source /opt/st/SDK/environment-setup-cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi
        cmake --preset arm-release
        cmake --build --preset arm-release
