name: build

on: [push, pull_request]

jobs:
  host-and-arm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang clang-tidy zstd

      # ---------- SDK cache ----------
      - name: Restore STM32MP1 SDK
        uses: actions/cache@v4
        id: sdk
        with:
          path: /opt/st/SDK
          key: stm32mp1-sdk-6.6-scarthgap

      - name: (One-time) unpack SDK if cache miss
        if: steps.sdk.outputs.cache-hit != 'true'
        env:
          SDK_URL: ${{ secrets.SDK_URL }}   # create this secret OR hard-code the URL below
        run: |
          wget --quiet "$SDK_URL" -O /tmp/sdk.tar.zst
          sudo mkdir -p /opt/st
          sudo tar -I zstd -xf /tmp/sdk.tar.zst -C /opt/st/
          sudo /opt/st/SDK/st-image-weston-*.sh -y -d /opt/st/SDK

      # ---------- Build host ----------
      - name: Configure & build host-debug
        run: |
          cmake --preset host-debug
          cmake --build --preset host-debug
          ctest --preset host-debug --output-on-failure

      # ---------- Build ARM ----------
      - name: Configure & build arm-release
        run: |
          source /opt/st/SDK/environment-setup-cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi
          cmake --preset arm-release
          cmake --build --preset arm-release
